-- AlterTable: per-post SEO controls (all nullable)
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "metaDescription" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "ogTitle" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "ogDescription" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "ogImage" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "jsonLd" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "headHtml" TEXT;
